name = "sbir-backend"
main = "src/index.ts"
compatibility_date = "2026-02-23"

[[r2_buckets]]
bucket_name = "sbir-saas-bucket"
binding = "sbir_saas_bucket"

[[d1_databases]]
binding = "DB"
database_name = "sbir-saas-db"
database_id = "8cf8fed0-b543-4062-8ea0-948da21f251a"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "sbir_chunks"

[vars]
FRONTEND_URL = "https://sbir-grants.pages.dev"
BACKEND_URL = "https://sbir-backend.wayneq77.workers.dev"

compatibility_flags = ["nodejs_compat"]
